# Generated by Django 4.2.3 on 2024-09-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
    ]
