# Generated by Django 4.2.3 on 2024-09-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_movies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucements',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
