# Generated by Django 4.2.3 on 2024-09-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_annoucements_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucements',
            name='color',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
