# Generated by Django 4.2.3 on 2024-09-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_annoucements_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucements',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
