# Generated by Django 4.2.3 on 2024-09-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_alter_annoucements_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annoucements',
            options={'verbose_name': 'Annoucement', 'verbose_name_plural': 'Annoucements '},
        ),
        migrations.AlterModelOptions(
            name='moviecategory',
            options={'verbose_name': 'Movie Category', 'verbose_name_plural': 'Movie Categories'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie or TV Serie', 'verbose_name_plural': 'Movies and TV Series'},
        ),
        migrations.AlterModelOptions(
            name='spotify',
            options={'verbose_name': 'Spotify', 'verbose_name_plural': 'Spotify Playlist or Songs'},
        ),
        migrations.AlterModelOptions(
            name='spotifycategory',
            options={'verbose_name': 'Spotify', 'verbose_name_plural': 'Spotify Categories'},
        ),
        migrations.AlterModelOptions(
            name='webhookmessage',
            options={'verbose_name': 'Simple Webhook', 'verbose_name_plural': 'Simple Webhooks'},
        ),
    ]
